package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_perl//perl:perl.bzl", "perl_library")

perl_library ( 
    name = "gc_content",
    srcs = ["GC_Content.pm"]
)

perl_library ( 
    name = "revcomp",
    srcs = ["RevComp.pm"]
)
