use strict;
use warnings;

use FindBin qw($Bin);

use Test::More tests => 1;

use Genome::RevComp;

my $dna_file = "$FindBin::Bin/test_data/DNA.fasta";

open(FH, $dna_file) or die "Can't open $dna_file: $!";

my $name = <FH>;
chomp($name);

my $DNA = "";
while(<FH>) {
    chomp;
    $DNA = $DNA.$_;
}
close(FH);

my $DNArc  = Genome::RevComp::revcomp($DNA);

sleep 5;

my $expected_DNArc = "CTTCTGGAGTTTATTTGGGAGCAGCTGGGATGATGGGGACCCCACAT"
    . "CCATAGGGCTGGGAGGTCAGGGCAAGGGCAAGGGGAAGAGGAAAGAAGGGTGCCTGGAGAGGA"
    . "GCAGAACTGGGGTTGCCGGCCAGGCCAGCAGAGCGACACCCTAGACCGGGCCGTAGAAGCGCC"
    . "GATAGGCCTCCTGAAAGCCGATGTGGTCAGCCAACTCGTCACAGTCCGGATTGAGCTCACACA"
    . "CCTCCCTCCTGGGCTCCAGGGGATCCGGGTAGGGGACTGGGGCTCTGAGACACCCGACGTGGT"
    . "GGCATCAGCCCCCGTGCAAAATGCCCATCCCTCCTCTCCCTACACATGGGGCTCCAGGGTGCC"
    . "CACCAGGGCAGGCTGCCTGTACCCCCACCACAACCCAGAGAGGCCACTCCCTGCTGCAGCTCC"
    . "CCCACAGACCATCCCGGAGAGGCAGGGCCTTGGCCCAGCTCTGCCTTTTCTCTCACCCCAGCC"
    . "ATTGATACAGGTAGCGCCTGGGTCTCTTCACTACCTCGCTGCCCTCCTGCTTGGACACAAAGG"
    . "CTGTGGAGCAGAGGGGCAGGCATCAGGTGGCTCTGGGTTTGGGAGGATCAGGTGGGGAGCAGG"
    . "CTGGCCTTCCTGATGGCCAGACAGGAGGTGGCAGGAGTGGGGGAATGAGACTGAGGGACCAGG"
    . "GTGAGAGGGGAGGGTCCAGGAACCCATCAGGTCCATCCTCATACCTGCACCTTTGCTGGACTC"
    . "TGCACCGCTGGGCTTCGCACCTGCAAAGGAAAGGGAGCCTGGTTCACCCCAGCTCATCCCCAG"
    . "GGCCCTCATCCTCCTTCCCCTGCGTCTCGGGCAGCTTGCTCTTCCCTCCTCTCCCTCTGCAAG"
    . "GGCAGAGCTGGGGCAAATGGATTGAGCCTGCAACAAGGTGGTTAGACTGCAAAGGGACTGCCA"
    . "GCCAAAGGGGTGAGAAGAGGTGGGCCATGGTGCTTCCTCCTCTCAGCCCCCACTGCAATGCGG"
    . "CCTGAGGGGAGGTGGGGGCACTCACCTGCCTGGCCAGCGATGCAAAGTGCGGCCAGGGCCAAT"
    . "AGGGCGAGGAGTGTGAGGGCTCTCATGGTGTCTCGGTGGCTGCGCTGGGCTGCTGCTCAGGAC"
    . "TCAGCTGGCCTGCCCCGCCAGCCTCCAGCACTGTTTATACCCTCTGGGCTGTGCCCAGCGATG"
    . "AGGAGGGGCATGCCTGACCATGGTGCGGGCGGGTCTAGGGGGAATCTGCC";

is($DNArc, $expected_DNArc);


1;
